profiles:
  - "kufar"
  - "onliner"
  - "realt"
parser:
  check_time: 20m
  too_many_requests_limit: 5
  download_worker_count: 10
  clean_time: 6h
tarantool:
  servers:
    - "storage.sku:3301"
    - "replica.sku:3301"
  timeout: 10s
  reconnect_interval: 1s
