replicaCount: 1
image:
  repository: registry.digitalocean.com/sku4/repository
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred
nameOverride: "ad-parser"
fullnameOverride: "ad-parser"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: ad-parser

podSecurityContext: {}
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  create: true
  type: ClusterIP
  externalPort: 80
  internalPort: 8000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

volumes:
  - name: googlekeep
    secret:
      secretName: googlekeep
  - name: db
    persistentVolumeClaim:
      claimName: boltdb
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts:
  - name: db
    mountPath: /root/db
  - name: googlekeep
    mountPath: /root/configs/googlekeep
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

env:
  - name: TT_INSTANCE_NAME
    value: "master"
  - name: TT_INSTANCE_PORT
    value: "3301"
  - name: TT_REPLICATION
    value: "ad-tnt-master:3301,ad-tnt-replica:3302"

nodeSelector: {}

tolerations: []

affinity: {}


